name: LogTag

on:
  push:
    branches:
      - "main"
      - "develop/**"
    paths-ignore:
      - ".vscode/**"
      - "README.md"
      - "LICENSE"
      - "doc/**"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - ".vscode/**"
      - "README.md"
      - "LICENSE"
      - "doc/**"

jobs:
  docker-test:
    name: Test from Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make test script executable
        run: chmod +x test/1.run.sh

      - name: Run Test Script in test folder
        run: |
          cd test
          ./1.run.sh

  deploy-pypi:
    name: Deploy PyPi
    needs: docker-test
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
